export const forms = {
  Basic: {
    inpol: {
      id: "inpol",
      fieldName: "inpol",
      type: "number",
      className: "",
      labelName: "Номер внеска на inPol",
      placeholder: "00641410",
      maxlength: 8,
      minlength: 8,
      required: true,
      inputHelper: "Находится на заполненом внеске рядом со штрих кодом",
    },
    mos: {
      id: "mos",
      fieldName: "mos",
      type: "number",
      className: "",
      labelName: "Номер внеска на MOS",
      placeholder: "42354528",
      maxlength: 8,
      minlength: 8,
      required: true,
      inputHelper: "Находится на заполненом внеске рядом со штрих кодом",
    },
    name: {
      id: "name",
      fieldName: "name",
      type: "text",
      className: "",
      labelName: "Имя",
      placeholder: "Alexey",
      maxlength: 32,
      minlength: 2,
      required: true,
      inputHelper: "Как в загранпаспорте (Латинскими буквами)",
    },
    surname: {
      id: "surname",
      fieldName: "surname",
      type: "text",
      className: "",
      labelName: "Фамилия",
      placeholder: "Rzayev",
      maxlength: 32,
      minlength: 2,
      required: true,
      inputHelper: "Как в загранпаспорте (Латинскими буквами)",
    },
    nationality: {
      id: "nationality",
      fieldName: "nationality",
      type: "text",
      className: "",
      labelName: "Гражданство",
      placeholder: "Poland",
      maxlength: 32,
      minlength: 2,
      required: true,
      inputHelper: "Как в загранпаспорте (Латинскими буквами)",
    },
    birthday: {
      id: "birthday",
      fieldName: "birthday",
      type: "date",
      className: "",
      labelName: "Дата рождения",
      placeholder: "",
      maxlength: 32,
      minlength: 2,
      required: true,
      inputHelper: "",
    },
    passport: {
      id: "passport",
      fieldName: "passport",
      type: "text",
      className: "",
      labelName: "Номер паспорта",
      placeholder: "FA8243943",
      maxlength: 9,
      minlength: 9,
      required: true,
      inputHelper: "",
    },
    phone: {
      id: "phone",
      fieldName: "phone",
      type: "text",
      className: "",
      labelName: "Номер телефона",
      placeholder: "+48579137807",
      maxlength: 12,
      minlength: 12,
      required: false,
      inputHelper: "Для связи с нами",
    },
    email: {
      id: "email",
      fieldName: "email",
      type: "text",
      className: "",
      labelName: "Электронная почта",
      placeholder: "FA8243943",
      maxlength: 32,
      minlength: 2,
      required: true,
      inputHelper: "Для связи с нами",
    },
  },
};
